# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cc650daf5ee5f94c65c4d501dd34036faa1ad0ccb9200b7d265bda5ce7867c5a0c8ed77d0b432b32a3033fcdac4e012a79d196ed852d4697a2c76815b59461e

test:
  secret_key_base: ac0ef251c107140bdf2a405240a2665d170bed5e9323ff3ebcce53dcb2e21ca2751894b866daa62c3eebdc9dff2918a80f669149ea78323b6372a18b1bf8f011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
